# Урок 6

## Взаимосвязь величин. Показатели корреляции. Корреляционный анализ. Проверка на нормальность

In [1]:
import pandas as pd
import numpy as np
from scipy import stats as st
from matplotlib import pyplot as plt
from itertools import combinations
import warnings
warnings.filterwarnings("ignore")

### Задача 1

#### Даны значения величины заработной платы заемщиков банка (salary) и значения их поведенческого кредитного скоринга (scoring):

salary = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110]

scoring = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832]

#### 1. Найдите ковариацию этих двух величин: сначала без использования специальных функций, а затем с помощью функции numpy.cov. Полученные значения должны быть равны.

#### 2. Найдите коэффициент корреляции Пирсона: с помощью ковариации и средних квадратических отклонений двух признаков, а затем с помощью специальных функций из библиотек numpy и pandas.

In [2]:
df1 = pd.DataFrame([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
df2 = pd.DataFrame([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [3]:
X = df1[0]
Y = df2[0]
MX = X.mean()
MY = Y.mean()

In [4]:
cov_xy = ((X - MX) * (Y - MY)).sum() / (X.shape[0] - 1)
cov_xy

10175.37777777778

In [5]:
cov = np.cov(X, Y)
cov

array([[ 3882.93333333, 10175.37777778],
       [10175.37777778, 33854.32222222]])

##### cov_xy и cov равны до 10 знака после запятой

In [6]:
X.var(ddof=1), Y.var(ddof=1)

(3882.9333333333334, 33854.32222222223)

In [7]:
corr = cov / (X.std(ddof = 1) * Y.std(ddof = 1))
corr

array([[0.33866702, 0.88749009],
       [0.88749009, 2.95275283]])

In [8]:
np.corrcoef(X, Y)

array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])

### Задача 2

#### Измерены значения IQ выборки студентов, обучающихся в местных технических вузах:

#### 131, 125, 115, 122, 131, 115, 107, 99, 125, 111

#### Известно, что в генеральной совокупности IQ распределен нормально. Найдите доверительный интервал для математического ожидания с надежностью 0.95.

дисперсия неизвестна -> используется t-статистика

In [9]:
df = pd.DataFrame([131, 125, 115, 122, 131, 115, 107, 99, 125, 111])
n = df.shape[0]
p = 0.95
alpha = 1 - p
samples=df[0]
mean = samples.mean()
std = samples.std(ddof=1)

n, mean, std

(10, 118.1, 10.54566788359614)

In [10]:
t1 = st.t.ppf(alpha / 2, df=n - 1)
t2 = st.t.ppf(1 - alpha / 2, df=n - 1)

t1, t2

(-2.2621571627409915, 2.2621571627409915)

In [11]:
print(f'Доверительный интервал: {mean + t1 * std / np.sqrt(n), mean + t2 * std / np.sqrt(n)}')

Доверительный интервал: (110.55608365158724, 125.64391634841274)


### Задача 3

#### Известно, что рост футболистов в сборной распределен нормально с известной дисперсией 25. На выборке объёма 27 выборочное среднее составило 174.2. Найдите доверительный интервал для математического ожидания с надежностью 0.95.

дисперсия известна -> используется S-статистика

In [12]:
n = 27
p = 0.95
alpha = 1 - p
means = 174.2
sigma = np.sqrt(25) #сигма это корень из дисперсии

In [13]:
t1 = st.norm.ppf(alpha / 2)
t2 = st.norm.ppf(1 - alpha / 2)

t1, t2

(-1.959963984540054, 1.959963984540054)

In [14]:
P_left = means + t1 * sigma / np.sqrt(n)
P_right = means + t2 * sigma / np.sqrt(n)
print (f'Доверительный интервал: {P_left}, {P_right}')

Доверительный интервал: 172.3140237765397, 176.08597622346028
